#! /bin/bash

set -eu


# install neovim and dependencies
brew install neovim
brew tap homebrew/cask-fonts && brew install --cask font-ubuntu-mono-nerd-font


# install https://github.com/junegunn/vim-plug

sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

config_path=${HOME}/.config/nvim
config_file_path=${config_path}/init.vim
if [ ! -e $config_file_path ]; then
	mkdir -p ${config_path}
	ln -s ${PWD}/init.vim ${config_file_path}
fi

coc_config_file_path=${config_path}/coc-settings.json
if [ ! -e $coc_config_file_path ]; then
  ln -s ${PWD}/coc-settings.json ${coc_config_file_path}
fi

# Install color scheme
mkdir -p ~/.config/nvim/colors
curl https://raw.githubusercontent.com/w0ng/vim-hybrid/master/colors/hybrid.vim -o ~/.config/nvim/colors/hybrid.vim

