# add snap to path
append_to_path "/snap/bin"

abs_path="$(get_abs_path $0)"
# generated by `make build_init` from init/*/init.sh; absent on no_sudo installs
[ -f "${abs_path}/zsh/generated_init.zsh" ] && source "${abs_path}/zsh/generated_init.zsh"
