name: CI Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_macos:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.19'
    - name: Create .installignore
      run: touch ./init/.installignore
    - name: Initialize environments
      run: make
