name: CI Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_macos:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3

    - name: Initialize environments
      run: make
